### ISSUE TITLE
Question: react-native wrapper for iOS & Android sdks? 

### ISSUE THREAD

**Issue by kumarpatel** [Webtrekk/webtrekk-ios-sdk#14]
Is there one in the making or will there be one in the near future?

**Comment by olebahlmann** [comment]
@kumarpatel Currently there is no wrapper planned for the coming weeks. Please feel free to submit a PR. We can support you to some extend  if necessary.

**Comment by kumarpatel** [comment]
ok thanks. I'll post back when I have something to show for it. In the mean time, is it possible to use this iOS sdk in an Objective C project?
I have open issue (question) for this [here](https://github.com/Webtrekk/webtrekk-ios-sdk/issues/16)

**Comment by MBing** [comment]
I will close this as this would be more a future implementation for our Pixel Tracker (Web version) rather than for the SDK. The Pixel also has a lot more features and is more adjusted to the use of web API technologies. If we plan it later to do in the SDK, we can reopen it and will let you know. 😉
