### ISSUE TITLE
CryptoSwift has been updated to 0.6.9

### ISSUE THREAD

**Issue by drct** [Webtrekk/webtrekk-ios-sdk#20]
CryptoSwift has been updated to v0.6.9 while Webtrekk uses v0.6.7. Is the older version used on purpose?

**Comment by arsen-vartbaronov** [comment]
Dear @drct 
We plan to update version to the latest one. Do you have any specific issue because of that?

**Comment by drct** [comment]
I don't have specific issues at the moment, because I use CryptoSwift only through Webtrekk. But if I used it separately I might have.
I was also wondering why you have limited the dependency to one specific Version? You might exclude important bugfixes or features.

**Comment by pfrischmuth** [comment]
It would be nice if you could update CryptoSwift to something like `~> 0.6.9`. CryptoSwift does currently not compile with Xcode 9, but they already fixed this in their `develop` branch. This way we could overwrite the CryptoSwift dependency until they provide a new release.

**Comment by arsen-vartbaronov** [comment]
Hi, @drct and @pfrischmuth 
There are couple factors here:
1. We don't use this library a lot (actually only hash functions) and I would thinking about read of that, to avoid forcing other company to have dependency from this library. However so far there is no problem with library version we are using now.
2. Except important bug fixing there is also risk of API change. Per SemVer documentation 

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

So in other words changes from 0.6.7 to 0.6.8 version can be not compatible, as they can change already existed API. And if I put version like ~> 0.6.9 code in GitHub might not compile, just because they change/rename existed function and publish next version. That is why until version of Semantic won't became 1.0.0+ I don't fill it would be good to have flexible dependency from version number .
However if you need update version of CryptoSwift as soon as they published version compatible to Xcode 9, I can shortly provide update with new version. At the same time if version became 1.0.0+ I can provide release version with "~> 1.x.0"

**Comment by victorrodri04** [comment]
Hi @arsen-vartbaronov, 

I have the same issue. It would be great if you could provide with that provide with a new version earlier so we can start our migration with all the dependencies working. 

This will also speed up your migration process in case issues appear to be ready for day one. If everything is ready beforehand it will be a matter of verifying that everything works like in the betas.

It is pretty common to see this approach in many popular frameworks. 

Do you think this would be possible?

Many thanks,

Victor

**Comment by olebahlmann** [comment]
You can expect an update to CryptoSwift v0.6.9. shortly. There is also a Swift4 version for cocoapods coming.

**Comment by victorrodri04** [comment]
That's great. Thank you very much.

**Comment by olebahlmann** [comment]
We have released a new [version](https://github.com/Webtrekk/webtrekk-ios-sdk/releases/tag/4.7.0) that doesn't depend on cryptoswift anymore.
