### ISSUE TITLE
Automatic media tracking in WebView

### ISSUE THREAD

**Issue by KonradCLAPP** [Webtrekk/webtrekk-ios-sdk#7]
We are using webtrekk in an iOS App that has a WebView and automatic tracking enabled. Inside the Webviev we would like to track the events the user invokes (standard webtracking), including playing and pausing a `<video>` and which file is played.

Is it also possible to attach further properties of the video, like duration, id and so on and send that along the other data/events to the tracking?

**Comment by olebahlmann** [comment]
Hi KonradCLAPP,
generally your problem is not something you'd solve in the SDK. When you use the webview you need to have the Webtrekk Tracking Pixel on that web content to track pageviews and video interactions. To ensure that both SDK and tracking pixel are tracking into the same session, please refer to chapter 9 of the SDK documentation.
